//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace game_zelda_a_link_between_worlds.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("game_zelda_a_link_between_worlds.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vara de Gelo
        ///Vara de Areia
        ///Vara de Tornado
        ///Bombas
        ///Vara de Fogo
        ///Hookshot
        ///Bumerangue
        ///Martelo
        ///Arco
        ///Escudo
        ///Frasco
        ///Poção Vermelha
        ///Poção Azul
        ///Coração
        ///Bracelete do Ravio
        ///Lamparina
        ///Maiamai Perdido
        ///Moedas de Jogo
        ///Pedra Preciosa
        ///Fruta Desagradável
        ///Fruta da Fuga
        ///Pedaço de Coração
        ///Abelha
        ///Insígnea da Abelha
        ///Luva do Poder
        ///Luva de Titã
        ///Botas de Pégaso
        ///Sineta
        ///Óculos das Dicas
        ///Abelha Dourada
        ///Poção Amarela
        ///Poção Roxa
        ///Nadadeiras de Zora
        ///Rede
        ///Pendante da Sabedoria
        ///Pendante da Coragem
        ///Pendante do Poder
        ///Fada
        ///Minério Superior
        ///Esp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string item {
            get {
                return ResourceManager.GetString("item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palácio Oriental
        ///Casa dos Ventos
        ///Torre de Hera
        ///Castelo Hyrule
        ///Palácio Sombrio
        ///Palácio do Pântano
        ///Floresta da Caveira
        ///Vila dos Bandidos
        ///Ruínas de Gelo
        ///Palácio do Deserto
        ///Rocha da Tartaruga
        ///Castelo Lorule
        ///Igreja
        ///Vila Kakariko
        ///Lago Hylia
        ///Sua Casa
        ///Death Mountain
        ///Casa da Bruxa
        ///Torre Traiçoeira
        ///Vidente
        ///Cemitério
        ///Loja Mágica
        ///Ferreiro
        ///Casa Vaga
        ///Milk Bar
        ///Atoleiro do Tormento
        ///Domínio Zora
        ///Death Mountain
        ///Sala do Trono
        ///Desvie dos Cuccos
        ///Hyrule Hotfoot
        ///Estádio de Octoball
        ///Rupee Rush
        ///Vidente
        ///Lost Woods
        ///Toca dos Bandidos
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MainFont_bcfnt {
            get {
                object obj = ResourceManager.GetObject("MainFont_bcfnt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zelda
        ///Impa
        ///Osfala
        ///Oren
        ///Dampé
        ///Irene
        ///Seres
        ///Rosso
        ///priest
        ///Sahasrahla
        ///Ganon
        ///Hilda
        ///Ravio
        ///Yuga
        ///captain
        ///Hint Ghost
        ///Sheerow
        ///Gulley
        ///witch
        ///Mother Maiamai
        ///.
        /// </summary>
        internal static string npc {
            get {
                return ResourceManager.GetString("npc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap template {
            get {
                object obj = ResourceManager.GetObject("template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap textbox {
            get {
                object obj = ResourceManager.GetObject("textbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
